# Generated by Django 5.0.2 on 2024-03-04 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200)),
                ('CpfCNPJ', models.CharField(max_length=64)),
                ('Telefone', models.CharField(max_length=64)),
                ('Endereco', models.CharField(max_length=255)),
                ('Bairro', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
    ]
