# Generated by Django 5.0.2 on 2024-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagpix_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pix',
            old_name='Endereco',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='pix',
            name='Bairro',
        ),
        migrations.RemoveField(
            model_name='pix',
            name='CpfCNPJ',
        ),
        migrations.RemoveField(
            model_name='pix',
            name='Telefone',
        ),
        migrations.AddField(
            model_name='pix',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pix',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='pix',
            name='cidade',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pix',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pix',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='bairro',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='cpfCNPJ',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='telefone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
