# Generated by Django 5.0.2 on 2024-03-04 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagpix_app', '0002_rename_endereco_pix_email_remove_pix_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='callback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='comentarios',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='dataDesconto1',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pix',
            name='dataDesconto2',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pix',
            name='desconto1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pix',
            name='desconto2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pix',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pix',
            name='modoJuros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pix',
            name='modoMulta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pix',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pix',
            name='nNum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='nrDoc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pix',
            name='originId',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='pix',
            name='validade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pix',
            name='vencimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
