# Generated by Django 5.0.3 on 2024-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagpix_app', '0003_pix_callback_pix_comentarios_pix_datadesconto1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
